StateMachine/src/StateMachine.Web/Controllers/SimpleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StateMachine.Web.Models;

namespace StateMachine.Web.Controllers
{
    public class SimpleController : Controller
    {
        static readonly List<Order> simpleOrders = new List<Order>()
        {
            new Order(1,"衣服","80",150),
            new Order(2,"裤子","443",100),
            new Order(3,"鞋子","3306",200),
            new Order(4,"袜子","9527",50),
        };

        public IActionResult Index()
        {
            return View(simpleOrders);
        }
    }
}

StateMachine/src/StateMachine.Web/Views/Simple/Index.cshtml
@model List<Order>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <table class="table">
        <thead>
            <tr>
                <th>编号</th>
                <th>名称</th>
                <th>价格</th>
                <th>状态</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var order in Model)
            {
                <tr>
                    <td>@order.OrderNo</td>
                    <td>@order.OrderName</td>
                    <td>@order.Price</td>
                    <td>@order.OrderState</td>
                    @switch (order.OrderState)
                    {
                        case OrderState.OrderCreated:
                            <td>
                                <a class="btn btn-primary" href="@Url.Action("UpdateOrderState","Simple",new {operateResult=OperateEnum.Agree })">跳转支付</a>
                                <a class="btn btn-primary" href="@Url.Action("UpdateOrderState","Simple",new {operateResult=OperateEnum.Disagree })">取消订单</a>
                            </td>
                            break;
                        case OrderState.OrderPendingPay:
                            <td>
                                <a class="btn btn-primary" href="@Url.Action("UpdateOrderState","Simple",new {operateResult=OperateEnum.Agree })">完成支付</a>
                                <a class="btn btn-primary" href="@Url.Action("UpdateOrderState","Simple",new {operateResult=OperateEnum.Disagree })">取消订单</a>
                            </td>
                            break;
                        case OrderState.OrderPendingSend:
                            <td>
                                <a class="btn btn-primary" href="@Url.Action("UpdateOrderState","Simple",new {operateResult=OperateEnum.Agree })">完成配送</a>
                                <a class="btn btn-primary" href="@Url.Action("UpdateOrderState","Simple",new {operateResult=OperateEnum.Disagree })">取消订单</a>
                            </td>
                            break;
                        case OrderState.OrderPendingSign:
                            <td>
                                <a class="btn btn-primary" href="@Url.Action("UpdateOrderState","Simple",new {operateResult=OperateEnum.Agree })">完成收货</a>
                            </td>
                            break;
                        default:
                            break;
                    }
                </tr>
            }
        </tbody>
    </table>
</div>